'''
ManualGaitAnalyzer :

@Author : Designed by Kai-Tang T., implemented with the assistance of Gemini AI (and Validated by KT).'

@LastUpdate : 6/24/2026

@UpdateLog:

* 6/23/26 : Uses Gemini AI to create the structure of the code following ideas from KT. Incorporating convertion ratio logic by getting pixel distance and user define real world distance. Takes three points to denote the coordinate and frame of hindpaw movements on each leg to output stride length and speed. Validated the output generated to be similar to the one generated by PrAnCER program. Sanity Check the output falls within expected ranges.

* 6/24/26 : Added the feature to remove the last points (for editing ability for misclicks). Within a folder, save all the different MUID (videos) within the same .csv file, different rows indicating different MUID.

* 7/7/26 : Added Base of Support calculations. (This include only the y-coordinate calculation due to accounting that with tunnel design, the mice can only move in one direction.)

* 7/20/26 : Added a pause after inputting points and require the user the press "ENTER" before moving onto the next step.

* 8/3/26 : Added dynamic point-count per hind paw, replacing the previous hardcoded 3-point limit per side. Users can now determine how many paw coordinates are collected for analysis. Increasing the number of points allows more strides to contribute to the average gait parameters. Default / Minimum value is 3 points per side.

* 8/4/26 : Added TkMessageBox instruction prompts when the maximum required point count for a hind paw is reached. If points are removed and the maximum count is reached again, the instruction prompt will reappear.

* 
'''

import cv2
import numpy as np
import os
import math
import pandas as pd
import tkinter as tk
from tkinter import filedialog
from tkinter import simpledialog
import tkinter.messagebox as tkMessageBox

# Global Variables for Tracking State
clicked_points = []  # Stores the coordinates (spatial) and the specific frame (temporal) of each clicked points.
current_stage = "CALIBRATION"  # Stages: CALIBRATION, HIND_RIGHT, HIND_LEFT, DONE
frame_idx = 0  # Shared the current frame with mouse_callback functions.

# Dynamic thresholds set by user at runtime (defaulting to 3 points per side)
pts_per_side = 3
max_right_idx = 2 + 3       # Calibration takes indices 0, 1 -> Right starts at index 2
max_left_idx = 2 + 3 + 3   # Left starts immediately after Right

# This functions specify that in the event of a mice click, it saves the coordinate and the frame within clicked_points.
def mouse_callback(event, x, y, flags, param):
    global clicked_points, current_stage, frame_idx, pts_per_side, max_right_idx, max_left_idx
    if event == cv2.EVENT_LBUTTONDOWN:
        if current_stage == "CALIBRATION" and len(clicked_points) < 2:
            clicked_points.append((x, y, frame_idx))
            if len(clicked_points) == 2:
                print("Calibration points captured. Press ENTER to confirm real distance.")
        elif current_stage == "HIND_RIGHT" and len(clicked_points) < max_right_idx:
            clicked_points.append((x, y, frame_idx))
            print(f"Captured Hind Right Print #{len(clicked_points) - 2} at frame {frame_idx}")
        elif current_stage == "HIND_LEFT" and len(clicked_points) < max_left_idx:
            clicked_points.append((x, y, frame_idx))
            print(f"Captured Hind Left Print #{len(clicked_points) - max_right_idx} at frame {frame_idx}")


def main():
    global clicked_points, current_stage, frame_idx, pts_per_side, max_right_idx, max_left_idx

    # 1. Select Video File
    root = tk.Tk()
    root.withdraw()
    video_path = filedialog.askopenfilename(title="Select Video File for Manual Analysis")

    if not video_path:
        print("No file selected. Exiting.")
        return

    # Prompt user for the number of points per hind leg side (minimum 2 points required to calculate at least 1 stride)
    pts_input = simpledialog.askinteger("Configuration", "Enter number of points to click per hind paw:", initialvalue=3, minvalue=3)
    if pts_input is None:
        print("No point count entered. Exiting.")
        return
    
    pts_per_side = pts_input
    # Index boundaries dynamically defined based on user configuration:
    # Index 0, 1 -> Calibration
    # Index 2 to (2 + pts_per_side - 1) -> Hind Right
    # Index (2 + pts_per_side) to (2 + 2*pts_per_side - 1) -> Hind Left
    max_right_idx = 2 + pts_per_side
    max_left_idx = 2 + (2 * pts_per_side)

    # Generate the output file name based on the directory/folder that the video is in
    video_dir = os.path.dirname(video_path)
    folder_name = os.path.basename(video_dir)
    output_file = os.path.join(video_dir, f"{folder_name}_EasyGait_Parameter.csv")

    # Obtain the MUID of each video based on the video filename
    video_name = os.path.basename(video_path)
    muid = os.path.splitext(video_name)[0]

    # 2. Extract Native Video Properties
    cap = cv2.VideoCapture(video_path)
    total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
    fps = cap.get(cv2.CAP_PROP_FPS) #Get FPS, this is important for the Temporal Parameteres

    if fps <= 0 or math.isnan(fps):
        fps = 30.0

    # Read first frame for calibration
    ret, frame = cap.read()
    if not ret:
        print("Error reading video file.")
        cap.release()
        return

    #Resize the screeen so regardless of the size of the video, it can always be displayed on computer.
    display_w, display_h = 800, 600
    first_frame_resized = cv2.resize(frame, (display_w, display_h))

    # 3. Stage 1: Calibration (Points 1 & 2)
    window_title = f"EasyGait - {video_name}"
    cv2.namedWindow(window_title)
    cv2.setMouseCallback(window_title, mouse_callback)

    tkMessageBox.showinfo("Step 1: Calibration",
                          "Click TWO points to mark a known reference distance.\nPress ENTER to confirm.\nPress 'C' to clear last point.")

    isRightFinished = False
    isLeftFinished = False

    while True:
        img_copy = first_frame_resized.copy()

        # Click two points, each points will display Cal 1 or 2
        for i, pt in enumerate(clicked_points[:2]):
            cv2.circle(img_copy, (pt[0], pt[1]), 5, (0, 0, 255), -1)
            cv2.putText(img_copy, f"Cal {i + 1}", (pt[0] + 8, pt[1] + 5), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (0, 0, 255), 1)

        # Once clicked two points, connect them
        if len(clicked_points) == 2:
            cv2.line(img_copy, (clicked_points[0][0], clicked_points[0][1]),
                     (clicked_points[1][0], clicked_points[1][1]), (0, 255, 0), 2)

        cv2.imshow(window_title, img_copy)
        key = cv2.waitKey(30) & 0xFF

        # Once two points are clicked and press enter, finish the Calibration settings
        if key == 13 and len(clicked_points) == 2:  # ENTER
            break
        # If press the button C regardless of capitalization, it can undo the last point
        elif key == ord('c') or key == ord('C'):
            if len(clicked_points) > 0:
                clicked_points.pop()
                print("Last calibration point removed.")

    # Calculate Pixel Distance between the two points.
    (cx1, cy1, _), (cx2, cy2, _) = clicked_points[0], clicked_points[1]
    pixel_distance = math.sqrt((cx2 - cx1) ** 2 + (cy2 - cy1) ** 2)

    # Prompt user for real world distance of the drawn scale
    real_distance_cm = simpledialog.askfloat("Calibration Scale", "Enter real-world distance in cm:", minvalue=0.001)

    if real_distance_cm is None or real_distance_cm <= 0:
        print("Invalid calibration. Exiting.")
        cv2.destroyAllWindows()
        cap.release()
        return

    # Calculate the convertion ratio between Pixel Distance and Real Distance. With this calibration
    # Any data generated in pixel distance can multiply this conversion ratio to output real world distance (cm).
    cm_per_pixel = (real_distance_cm / pixel_distance)
    print(f"Calibration Set: {cm_per_pixel:.5f} cm/pixel | Video Framerate: {fps:.2f} FPS")

    # 4. Interactive Gait Video Player Settings
    current_stage = "HIND_RIGHT"
    tkMessageBox.showinfo("Step 2: Track Path",
                          f"Use trackbar to navigate time.\nPress SPACEBAR to Pause/Play.\nClick {pts_per_side} consecutive Hind Right steps.\nPress 'C' to Undo last point.\nPress 'ENTER' when finished")

    frame_idx = 0
    is_playing = True
    playback_speed = 100
    cv2.createTrackbar("Timeline", window_title, 0, total_frames - 1, lambda val: None)

    # 5. Continuous Slow Motion Playback Loop
    while current_stage != "DONE":
        trackbar_pos = cv2.getTrackbarPos("Timeline", window_title)
        if not is_playing:
            frame_idx = trackbar_pos
        else:
            cv2.setTrackbarPos("Timeline", window_title, frame_idx)

        cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
        ret, frame = cap.read()

        # Looping logic if end of video is reached
        if not ret:
            frame_idx = 0
            cv2.setTrackbarPos("Timeline", window_title, frame_idx)
            cap.set(cv2.CAP_PROP_POS_FRAMES, frame_idx)
            ret, frame = cap.read()
            if not ret:
                print("Error looping video file.")
                break

        frame_resized = cv2.resize(frame, (display_w, display_h))

        cv2.putText(frame_resized, f"Stage: Click {pts_per_side} {current_stage.replace('_', ' ')} Points", (15, 30),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.6, (255, 255, 255), 2)
        cv2.putText(frame_resized, f"Frame: {frame_idx} / {total_frames - 1} | [Space]: Pause | [C]: Undo", (15, 55),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.4, (200, 200, 200), 1)

        # Dynamic Drawing for Hind Right Paws. Right paw clicks reside in indices [2 : max_right_idx]
        if len(clicked_points) >= 3:
            right_end_idx = min(len(clicked_points), max_right_idx)
            for j in range(2, right_end_idx):
                pt = clicked_points[j]
                cv2.circle(frame_resized, (pt[0], pt[1]), 6, (255, 191, 0), -1)
                cv2.putText(frame_resized, f"R{j - 1}", (pt[0] + 8, pt[1]), cv2.FONT_HERSHEY_SIMPLEX, 0.5,
                            (255, 191, 0), 2)
                # Connect consecutive points with a line
                if j > 2:
                    cv2.line(frame_resized, (clicked_points[j - 1][0], clicked_points[j - 1][1]),
                             (clicked_points[j][0], clicked_points[j][1]), (255, 191, 0), 2)

            
            if len(clicked_points) >= max_right_idx and not isRightFinished:
                isRightFinished = True
                tkMessageBox.showinfo(
                    "Finished Collecting Right Hind Leg",
                    f"Finished collecting {pts_per_side} Right Coordinates.\n\n"
                    "Click OK, then click back into the EasyGait window.\n"
                    "Press [ENTER] to begin marking the Left Hind Leg.\n"
                    "Press [C] to undo any points."
                )
            if len(clicked_points) < max_right_idx:
                isRightFinished = False

        # Dynamic Drawing for Hind Left Paws. Left paw clicks reside in indices [max_right_idx : max_left_idx]
        if len(clicked_points) >= max_right_idx + 1:
            cv2.putText(frame_resized, f"Frame: {frame_idx} / {total_frames - 1} | [Space]: Pause | [C]: Undo", (15, 55),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.4, (200, 200, 200), 1)

            left_end_idx = min(len(clicked_points), max_left_idx)
            for k in range(max_right_idx, left_end_idx):
                pt = clicked_points[k]
                cv2.circle(frame_resized, (pt[0], pt[1]), 6, (0, 69, 255), -1)
                cv2.putText(frame_resized, f"L{k - max_right_idx + 1}", (pt[0] + 8, pt[1]), cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 69, 255),
                            2)
                # Connect consecutive points with a line
                if k > max_right_idx:
                    cv2.line(frame_resized, (clicked_points[k - 1][0], clicked_points[k - 1][1]),
                             (clicked_points[k][0], clicked_points[k][1]), (0, 69, 255), 2)

            if len(clicked_points) >= max_left_idx and not isLeftFinished:
                isLeftFinished = True
                tkMessageBox.showinfo(
                    "Finished Collecting Left Hind Leg",
                    f"Finished collecting {pts_per_side} Left Coordinates.\n\n"
                    "Click OK, then click back into the EasyGait window.\n"
                    "Press [ENTER] to complete gait analysis.\n"
                    "Press [C] to undo any points."
                )

            if len(clicked_points) < max_left_idx:
                isLeftFinished = False

        cv2.imshow(window_title, frame_resized)

        # User key functions. Space pause the video, enter just finish calculation, C undo the last point.
        key = cv2.waitKey(playback_speed if is_playing else 30) & 0xFF
        if key == 32:  # SPACEBAR
            is_playing = not is_playing
        elif key == 13:  # ENTER
            if current_stage == "HIND_RIGHT" and len(clicked_points) == max_right_idx:
                current_stage = "HIND_LEFT"
                tkMessageBox.showinfo("Step 3: Track Hind Left",
                                      f"Hind Right registered.\nNow click {pts_per_side} consecutive Hind Left steps.")
            elif current_stage == "HIND_LEFT" and len(clicked_points) == max_left_idx:
                current_stage = "DONE"
                tkMessageBox.showinfo("Step 4: Confirm Data", 
                                      "Hind Left registered. EasyGait Completes.")
            elif current_stage == "DONE":
                break
        elif key == ord('c') or key == ord('C'):  # Undo functionality
            if len(clicked_points) > 2:  # Do not delete calibration points here
                popped = clicked_points.pop()
                print(f"Removed last tracked point. Total points: {len(clicked_points)}")
                # Reset tracking stage if rolled back below right paw quota
                if len(clicked_points) < max_right_idx:
                    current_stage = "HIND_RIGHT"
        elif key == 27:  # ESC. End the program does not output anything.
            cv2.destroyAllWindows()
            cap.release()
            return

        if is_playing:
            frame_idx += 1
            if frame_idx >= total_frames:
                frame_idx = 0  # Force loop restart index initialization

    cv2.destroyAllWindows()
    cap.release()

    # 6. Complete Mathematical & Structural Row Output System
    if len(clicked_points) == max_left_idx:
        # Extract Right and Left paw tracking sequences dynamically
        right_pts = clicked_points[2 : max_right_idx]
        left_pts = clicked_points[max_right_idx : max_left_idx]

        # Base of Support (BOS) Calculations (Simplified Y-Axis Only across paired points)
        cm_bos_list = []
        for idx in range(pts_per_side):
            px_bos = abs(left_pts[idx][1] - right_pts[idx][1])
            cm_bos_list.append(px_bos * cm_per_pixel)
        cm_bos_avg = sum(cm_bos_list) / len(cm_bos_list)

        # Dynamic calculation of Right Stride Lengths, Durations, and Velocities
        cm_r_list = []
        t_r_list = []
        sp_r_list = []
        for i in range(len(right_pts) - 1):
            p_start, p_end = right_pts[i], right_pts[i + 1]
            px_dist = math.hypot(p_end[0] - p_start[0], p_end[1] - p_start[1])
            cm_dist = px_dist * cm_per_pixel
            cm_r_list.append(cm_dist)

            t_duration = abs(p_end[2] - p_start[2]) / fps
            t_r_list.append(t_duration)

            speed = cm_dist / t_duration if t_duration > 0 else 0
            sp_r_list.append(speed)

        # Dynamic calculation of Left Stride Lengths, Durations, and Velocities
        cm_l_list = []
        t_l_list = []
        sp_l_list = []
        for i in range(len(left_pts) - 1):
            p_start, p_end = left_pts[i], left_pts[i + 1]
            px_dist = math.hypot(p_end[0] - p_start[0], p_end[1] - p_start[1])
            cm_dist = px_dist * cm_per_pixel
            cm_l_list.append(cm_dist)

            t_duration = abs(p_end[2] - p_start[2]) / fps
            t_l_list.append(t_duration)

            speed = cm_dist / t_duration if t_duration > 0 else 0
            sp_l_list.append(speed)

        # Calculate Spatial Means for right, left, and overall average stride length
        cm_r_avg = sum(cm_r_list) / len(cm_r_list) if cm_r_list else 0
        cm_l_avg = sum(cm_l_list) / len(cm_l_list) if cm_l_list else 0
        all_cm_strides = cm_r_list + cm_l_list
        cm_overall_avg = sum(all_cm_strides) / len(all_cm_strides) if all_cm_strides else 0

        # Calculate Temporal Means for stride duration and speed
        all_t_durations = t_r_list + t_l_list
        t_overall_avg = sum(all_t_durations) / len(all_t_durations) if all_t_durations else 0

        all_speeds = sp_r_list + sp_l_list
        sp_overall_avg = sum(all_speeds) / len(all_speeds) if all_speeds else 0

        # Formulate metrics row array using video filename as MUID
        new_row = {
            'MUID': [str(muid)],
            'Base of Support (cm)': [cm_bos_avg],
            'Average Stride (cm)': [cm_overall_avg],
            'Right Avg Stride (cm)': [cm_r_avg],
            'Left Avg Stride (cm)': [cm_l_avg],
            'AvgStride Duration (second)': [t_overall_avg],
            'Avg Stride Speed (cm / second)': [sp_overall_avg]
        }
        new_df = pd.DataFrame(new_row)

        # File Handling Logic: Check file existence, verify MUID status, rewrite or append
        if os.path.exists(output_file):
            try:
                existing_df = pd.read_csv(output_file)
                # Drop existing row matching MUID if present to enable a safe rewrite sequence
                if 'MUID' in existing_df.columns:
                    existing_df = existing_df[existing_df['MUID'].astype(str) != str(muid)]

                final_df = pd.concat([existing_df, new_df], ignore_index=True)
            except Exception as e:
                print(f"Error checking file, fallback to initialization pattern: {e}")
                final_df = new_df
        else:
            final_df = new_df

        # Save to localized disk location
        final_df.to_csv(output_file, index=False)
        print(f"\nAnalysis Saved Successfully to: {output_file}")
        tkMessageBox.showinfo("Success", f"Metrics updated for MUID (Video): {muid}\nFile Location: {output_file}")


if __name__ == '__main__':
    main()